### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by MeghnaW19** [Ashutoshkhamari/Muzix#5]
Muzix/src/main/java/com/stackroute/controller/MuzixApplicationListener.java

//    @Value("${track.id}")
//    private int trackid;
//
//    @Value("${track.name}")
//    private String trackName;
//
//    @Value("${track.comments}")
//    private String comments;

//    Track track=new Track(trackid,trackName,comments);

**Comment by Ashutoshkhamari** [comment]
ok
